notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b41d8d5ab227eca82bb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
language: node_js
node_js:
  - "0.10"
